#@TYPE: Machine
#@NAME: AXON-AM62XX
#@DESCRIPTION: Machine configuration for the TechNexion AXON-AM62XX

require conf/machine/include/am62xx.inc
require conf/machine/include/tn-base.inc

MACHINE_FEATURES += "gpu nxpiw416-sdio"

KERNEL_DEVICETREE_PREFIX = " \
    ti/k3-am625-axon \
"

KERNEL_DEVICETREE = " \
    ti/k3-am625-axon-wb.dtb \
    ti/k3-am625-axon-wb-lcd-vl050-070-8048.dtbo \
    ti/k3-am625-axon-wb-lcd-vl0808060.dtbo \
    ti/k3-am625-axon-wb-lvds-vl10112880.dtbo \
    ti/k3-am625-axon-wb-lvds-vl156192108.dtbo \
"

UBOOT_MACHINE = "axon-am62xx_a53_defconfig"

SERIAL_CONSOLES = "115200;ttyS2"
SERIAL_BLUETOOTH = "3000000;ttyS1"

