#@TYPE: Machine
#@NAME: AXON-AM62AX
#@DESCRIPTION: Machine configuration for the TechNexion AXON-AM62AX

require conf/machine/include/am62axx.inc
require conf/machine/include/tn-base.inc

MACHINE_FEATURES += "gpu nxpiw416-sdio"

KERNEL_DEVICETREE = " \
    ti/k3-am62a7-axon-wb.dtb \
"

UBOOT_MACHINE = "axon-am62ax_a53_defconfig"

SERIAL_CONSOLES = "115200;ttyS2"
SERIAL_BLUETOOTH = "3000000;ttyS1"

